{
    "openapi": "3.0.1",
    "info": {
        "title": "Slack Web API",
        "description": "One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.",
        "contact": {
            "name": "Slack developer relations",
            "url": "https://api.slack.com/support"
        },
        "version": "1.7.0"
    },
    "servers": [
        {
            "url": "https://slack.com/api"
        }
    ],
    "tags": [],
    "paths": {
        "/calls.add": {
            "post": {
                "tags": [
                    "calls"
                ],
                "description": "Registers a new Call.",
                "operationId": "calls_add",
                "security": [
                    {
                        "slackAuth": [
                            "calls:write"
                        ]
                    }
                ]
            }
        },
        "/calls.end": {
            "post": {
                "tags": [
                    "calls"
                ],
                "description": "Ends a Call.",
                "operationId": "calls_end",
                "security": [
                    {
                        "slackAuth": [
                            "calls:write"
                        ]
                    }
                ]
            }
        },
        "/calls.info": {
            "get": {
                "tags": [
                    "calls"
                ],
                "description": "Returns information about a Call.",
                "operationId": "calls_info",
                "security": [
                    {
                        "slackAuth": [
                            "calls:read"
                        ]
                    }
                ]
            }
        },
        "/calls.participants.add": {
            "post": {
                "tags": [
                    "calls.participants",
                    "calls"
                ],
                "description": "Registers new participants added to a Call.",
                "operationId": "calls_participants_add",
                "security": [
                    {
                        "slackAuth": [
                            "calls:write"
                        ]
                    }
                ]
            }
        },
        "/calls.participants.remove": {
            "post": {
                "tags": [
                    "calls.participants",
                    "calls"
                ],
                "description": "Registers participants removed from a Call.",
                "operationId": "calls_participants_remove",
                "security": [
                    {
                        "slackAuth": [
                            "calls:write"
                        ]
                    }
                ]
            }
        },
        "/calls.update": {
            "post": {
                "tags": [
                    "calls"
                ],
                "description": "Updates information about a Call.",
                "operationId": "calls_update",
                "security": [
                    {
                        "slackAuth": [
                            "calls:write"
                        ]
                    }
                ]
            }
        },
        "/chat.delete": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Deletes a message.",
                "operationId": "chat_delete",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/chat.deleteScheduledMessage": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Deletes a pending scheduled message from the queue.",
                "operationId": "chat_deleteScheduledMessage",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/chat.getPermalink": {
            "get": {
                "tags": [
                    "chat"
                ],
                "description": "Retrieve a permalink URL for a specific extant message",
                "operationId": "chat_getPermalink",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/chat.meMessage": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Share a me message into a channel.",
                "operationId": "chat_meMessage",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/chat.postEphemeral": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Sends an ephemeral message to a user in a channel.",
                "operationId": "chat_postEphemeral",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/chat.postMessage": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Post messages to public channels, private channels, direct messages, and multi-person direct messages.",
                "operationId": "chat_postMessage",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/chat.scheduleMessage": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Schedules a message to be sent to a channel.",
                "operationId": "chat_scheduleMessage",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/chat.scheduledMessages.list": {
            "get": {
                "tags": [
                    "chat.scheduledMessages",
                    "chat"
                ],
                "description": "Returns a list of scheduled messages.",
                "operationId": "chat_scheduledMessages_list",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/chat.unfurl": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Provide custom unfurl behavior for user-posted URLs",
                "operationId": "chat_unfurl",
                "security": [
                    {
                        "slackAuth": [
                            "links:write"
                        ]
                    }
                ]
            }
        },
        "/chat.update": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Updates a message.",
                "operationId": "chat_update",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/conversations.archive": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Archives a conversation.",
                "operationId": "conversations_archive",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.close": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Closes a direct message or multi-person direct message.",
                "operationId": "conversations_close",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.create": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Creates a new public or private channel.",
                "operationId": "conversations_create",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.history": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Fetches a conversation's history of messages and events.",
                "operationId": "conversations_history",
                "security": [
                    {
                        "slackAuth": [
                            "channels:history",
                            "groups:history",
                            "im:history",
                            "mpim:history"
                        ]
                    }
                ]
            }
        },
        "/conversations.info": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Retrieve information about a conversation.",
                "operationId": "conversations_info",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/conversations.invite": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Invites users to a channel.",
                "operationId": "conversations_invite",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.join": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Joins an existing conversation.",
                "operationId": "conversations_join",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.kick": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Removes a user from a conversation.",
                "operationId": "conversations_kick",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.leave": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Leaves a conversation.",
                "operationId": "conversations_leave",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.list": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Lists all channels in a Slack team.",
                "operationId": "conversations_list",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/conversations.mark": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Sets the read cursor in a channel.",
                "operationId": "conversations_mark",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.members": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Retrieve members of a conversation.",
                "operationId": "conversations_members",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/conversations.open": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Opens or resumes an existing direct message or multi-person direct message.",
                "operationId": "conversations_open",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.rename": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Renames a conversation.",
                "operationId": "conversations_rename",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.replies": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Retrieve a thread of messages posted to a conversation",
                "operationId": "conversations_replies",
                "security": [
                    {
                        "slackAuth": [
                            "channels:history",
                            "groups:history",
                            "im:history",
                            "mpim:history"
                        ]
                    }
                ]
            }
        },
        "/conversations.setPurpose": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Sets the purpose for a conversation.",
                "operationId": "conversations_setPurpose",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.setTopic": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Sets the topic for a conversation.",
                "operationId": "conversations_setTopic",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.unarchive": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Reverses conversation archival.",
                "operationId": "conversations_unarchive",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/dialog.open": {
            "get": {
                "tags": [
                    "dialog"
                ],
                "description": "Open a dialog with a user",
                "operationId": "dialog_open",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/dnd.endDnd": {
            "post": {
                "tags": [
                    "dnd"
                ],
                "description": "Ends the current user's Do Not Disturb session immediately.",
                "operationId": "dnd_endDnd",
                "security": [
                    {
                        "slackAuth": [
                            "dnd:write"
                        ]
                    }
                ]
            }
        },
        "/dnd.endSnooze": {
            "post": {
                "tags": [
                    "dnd"
                ],
                "description": "Ends the current user's snooze mode immediately.",
                "operationId": "dnd_endSnooze",
                "security": [
                    {
                        "slackAuth": [
                            "dnd:write"
                        ]
                    }
                ]
            }
        },
        "/dnd.info": {
            "get": {
                "tags": [
                    "dnd"
                ],
                "description": "Retrieves a user's current Do Not Disturb status.",
                "operationId": "dnd_info",
                "security": [
                    {
                        "slackAuth": [
                            "dnd:read"
                        ]
                    }
                ]
            }
        },
        "/dnd.setSnooze": {
            "post": {
                "tags": [
                    "dnd"
                ],
                "description": "Turns on Do Not Disturb mode for the current user, or changes its duration.",
                "operationId": "dnd_setSnooze",
                "security": [
                    {
                        "slackAuth": [
                            "dnd:write"
                        ]
                    }
                ]
            }
        },
        "/dnd.teamInfo": {
            "get": {
                "tags": [
                    "dnd"
                ],
                "description": "Retrieves the Do Not Disturb status for up to 50 users on a team.",
                "operationId": "dnd_teamInfo",
                "security": [
                    {
                        "slackAuth": [
                            "dnd:read"
                        ]
                    }
                ]
            }
        },
        "/emoji.list": {
            "get": {
                "tags": [
                    "emoji"
                ],
                "description": "Lists custom emoji for a team.",
                "operationId": "emoji_list",
                "security": [
                    {
                        "slackAuth": [
                            "emoji:read"
                        ]
                    }
                ]
            }
        },
        "/files.comments.delete": {
            "post": {
                "tags": [
                    "files.comments",
                    "files"
                ],
                "description": "Deletes an existing comment on a file.",
                "operationId": "files_comments_delete",
                "security": [
                    {
                        "slackAuth": [
                            "files:write:user"
                        ]
                    }
                ]
            }
        },
        "/files.delete": {
            "post": {
                "tags": [
                    "files"
                ],
                "description": "Deletes a file.",
                "operationId": "files_delete",
                "security": [
                    {
                        "slackAuth": [
                            "files:write:user"
                        ]
                    }
                ]
            }
        },
        "/pins.add": {
            "post": {
                "tags": [
                    "pins"
                ],
                "description": "Pins an item to a channel.",
                "operationId": "pins_add",
                "security": [
                    {
                        "slackAuth": [
                            "pins:write"
                        ]
                    }
                ]
            }
        },
        "/pins.list": {
            "get": {
                "tags": [
                    "pins"
                ],
                "description": "Lists items pinned to a channel.",
                "operationId": "pins_list",
                "security": [
                    {
                        "slackAuth": [
                            "pins:read"
                        ]
                    }
                ]
            }
        },
        "/pins.remove": {
            "post": {
                "tags": [
                    "pins"
                ],
                "description": "Un-pins an item from a channel.",
                "operationId": "pins_remove",
                "security": [
                    {
                        "slackAuth": [
                            "pins:write"
                        ]
                    }
                ]
            }
        },
        "/reactions.add": {
            "post": {
                "tags": [
                    "reactions"
                ],
                "description": "Adds a reaction to an item.",
                "operationId": "reactions_add",
                "security": [
                    {
                        "slackAuth": [
                            "reactions:write"
                        ]
                    }
                ]
            }
        },
        "/reactions.get": {
            "get": {
                "tags": [
                    "reactions"
                ],
                "description": "Gets reactions for an item.",
                "operationId": "reactions_get",
                "security": [
                    {
                        "slackAuth": [
                            "reactions:read"
                        ]
                    }
                ]
            }
        },
        "/reactions.list": {
            "get": {
                "tags": [
                    "reactions"
                ],
                "description": "Lists reactions made by a user.",
                "operationId": "reactions_list",
                "security": [
                    {
                        "slackAuth": [
                            "reactions:read"
                        ]
                    }
                ]
            }
        },
        "/reactions.remove": {
            "post": {
                "tags": [
                    "reactions"
                ],
                "description": "Removes a reaction from an item.",
                "operationId": "reactions_remove",
                "security": [
                    {
                        "slackAuth": [
                            "reactions:write"
                        ]
                    }
                ]
            }
        },
        "/reminders.add": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "description": "Creates a reminder.",
                "operationId": "reminders_add",
                "security": [
                    {
                        "slackAuth": [
                            "reminders:write"
                        ]
                    }
                ]
            }
        },
        "/reminders.complete": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "description": "Marks a reminder as complete.",
                "operationId": "reminders_complete",
                "security": [
                    {
                        "slackAuth": [
                            "reminders:write"
                        ]
                    }
                ]
            }
        },
        "/reminders.delete": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "description": "Deletes a reminder.",
                "operationId": "reminders_delete",
                "security": [
                    {
                        "slackAuth": [
                            "reminders:write"
                        ]
                    }
                ]
            }
        },
        "/reminders.info": {
            "get": {
                "tags": [
                    "reminders"
                ],
                "description": "Gets information about a reminder.",
                "operationId": "reminders_info",
                "security": [
                    {
                        "slackAuth": [
                            "reminders:read"
                        ]
                    }
                ]
            }
        },
        "/reminders.list": {
            "get": {
                "tags": [
                    "reminders"
                ],
                "description": "Lists all reminders created by or for a given user.",
                "operationId": "reminders_list",
                "security": [
                    {
                        "slackAuth": [
                            "reminders:read"
                        ]
                    }
                ]
            }
        },
        "/rtm.connect": {
            "get": {
                "tags": [
                    "rtm"
                ],
                "description": "Starts a Real Time Messaging session.",
                "operationId": "rtm_connect",
                "security": [
                    {
                        "slackAuth": [
                            "rtm:stream"
                        ]
                    }
                ]
            }
        },
        "/search.messages": {
            "get": {
                "tags": [
                    "search"
                ],
                "description": "Searches for messages matching a query.",
                "operationId": "search_messages",
                "security": [
                    {
                        "slackAuth": [
                            "search:read"
                        ]
                    }
                ]
            }
        },
        "/stars.add": {
            "post": {
                "tags": [
                    "stars"
                ],
                "description": "Adds a star to an item.",
                "operationId": "stars_add",
                "security": [
                    {
                        "slackAuth": [
                            "stars:write"
                        ]
                    }
                ]
            }
        },
        "/stars.list": {
            "get": {
                "tags": [
                    "stars"
                ],
                "description": "Lists stars for a user.",
                "operationId": "stars_list",
                "security": [
                    {
                        "slackAuth": [
                            "stars:read"
                        ]
                    }
                ]
            }
        },
        "/stars.remove": {
            "post": {
                "tags": [
                    "stars"
                ],
                "description": "Removes a star from an item.",
                "operationId": "stars_remove",
                "security": [
                    {
                        "slackAuth": [
                            "stars:write"
                        ]
                    }
                ]
            }
        },
        "/team.profile.get": {
            "get": {
                "tags": [
                    "team.profile",
                    "team"
                ],
                "description": "Retrieve a team's profile.",
                "operationId": "team_profile_get",
                "security": [
                    {
                        "slackAuth": [
                            "users.profile:read"
                        ]
                    }
                ]
            }
        },
        "/usergroups.create": {
            "post": {
                "tags": [
                    "usergroups"
                ],
                "description": "Create a User Group",
                "operationId": "usergroups_create",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:write"
                        ]
                    }
                ]
            }
        },
        "/usergroups.disable": {
            "post": {
                "tags": [
                    "usergroups"
                ],
                "description": "Disable an existing User Group",
                "operationId": "usergroups_disable",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:write"
                        ]
                    }
                ]
            }
        },
        "/usergroups.enable": {
            "post": {
                "tags": [
                    "usergroups"
                ],
                "description": "Enable a User Group",
                "operationId": "usergroups_enable",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:write"
                        ]
                    }
                ]
            }
        },
        "/usergroups.list": {
            "get": {
                "tags": [
                    "usergroups"
                ],
                "description": "List all User Groups for a team",
                "operationId": "usergroups_list",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:read"
                        ]
                    }
                ]
            }
        },
        "/usergroups.update": {
            "post": {
                "tags": [
                    "usergroups"
                ],
                "description": "Update an existing User Group",
                "operationId": "usergroups_update",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:write"
                        ]
                    }
                ]
            }
        },
        "/usergroups.users.list": {
            "get": {
                "tags": [
                    "usergroups.users",
                    "usergroups"
                ],
                "description": "List all users in a User Group",
                "operationId": "usergroups_users_list",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:read"
                        ]
                    }
                ]
            }
        },
        "/usergroups.users.update": {
            "post": {
                "tags": [
                    "usergroups.users",
                    "usergroups"
                ],
                "description": "Update the list of users for a User Group",
                "operationId": "usergroups_users_update",
                "security": [
                    {
                        "slackAuth": [
                            "usergroups:write"
                        ]
                    }
                ]
            }
        },
        "/users.conversations": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "List conversations the calling user may access.",
                "operationId": "users_conversations",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/users.deletePhoto": {
            "post": {
                "tags": [
                    "users"
                ],
                "description": "Delete the user profile photo",
                "operationId": "users_deletePhoto",
                "security": [
                    {
                        "slackAuth": [
                            "users.profile:write"
                        ]
                    }
                ]
            }
        },
        "/users.getPresence": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Gets user presence information.",
                "operationId": "users_getPresence",
                "security": [
                    {
                        "slackAuth": [
                            "users:read"
                        ]
                    }
                ]
            }
        },
        "/users.identity": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Get a user's identity.",
                "operationId": "users_identity",
                "security": [
                    {
                        "slackAuth": [
                            "identity.basic"
                        ]
                    }
                ]
            }
        },
        "/users.info": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Gets information about a user.",
                "operationId": "users_info",
                "security": [
                    {
                        "slackAuth": [
                            "users:read"
                        ]
                    }
                ]
            }
        },
        "/users.list": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Lists all users in a Slack team.",
                "operationId": "users_list",
                "security": [
                    {
                        "slackAuth": [
                            "users:read"
                        ]
                    }
                ]
            }
        },
        "/users.lookupByEmail": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Find a user with an email address.",
                "operationId": "users_lookupByEmail",
                "security": [
                    {
                        "slackAuth": [
                            "users:read.email"
                        ]
                    }
                ]
            }
        },
        "/users.profile.get": {
            "get": {
                "tags": [
                    "users.profile",
                    "users"
                ],
                "description": "Retrieves a user's profile information.",
                "operationId": "users_profile_get",
                "security": [
                    {
                        "slackAuth": [
                            "users.profile:read"
                        ]
                    }
                ]
            }
        },
        "/users.profile.set": {
            "post": {
                "tags": [
                    "users.profile",
                    "users"
                ],
                "description": "Set the profile information for a user.",
                "operationId": "users_profile_set",
                "security": [
                    {
                        "slackAuth": [
                            "users.profile:write"
                        ]
                    }
                ]
            }
        },
        "/users.setActive": {
            "post": {
                "tags": [
                    "users"
                ],
                "description": "Marked a user as active. Deprecated and non-functional.",
                "operationId": "users_setActive",
                "security": [
                    {
                        "slackAuth": [
                            "users:write"
                        ]
                    }
                ]
            }
        },
        "/users.setPhoto": {
            "post": {
                "tags": [
                    "users"
                ],
                "description": "Set the user profile photo",
                "operationId": "users_setPhoto",
                "security": [
                    {
                        "slackAuth": [
                            "users.profile:write"
                        ]
                    }
                ]
            }
        },
        "/users.setPresence": {
            "post": {
                "tags": [
                    "users"
                ],
                "description": "Manually sets user presence.",
                "operationId": "users_setPresence",
                "security": [
                    {
                        "slackAuth": [
                            "users:write"
                        ]
                    }
                ]
            }
        },
        "/views.open": {
            "get": {
                "tags": [
                    "views"
                ],
                "description": "Open a view for a user.",
                "operationId": "views_open",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/views.publish": {
            "get": {
                "tags": [
                    "views"
                ],
                "description": "Publish a static view for a User.",
                "operationId": "views_publish",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/views.push": {
            "get": {
                "tags": [
                    "views"
                ],
                "description": "Push a view onto the stack of a root view.",
                "operationId": "views_push",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/views.update": {
            "get": {
                "tags": [
                    "views"
                ],
                "description": "Update an existing view.",
                "operationId": "views_update",
                "security": [
                    {
                        "slackAuth": [
                            "none"
                        ]
                    }
                ]
            }
        },
        "/workflows.stepCompleted": {
            "get": {
                "tags": [
                    "workflows"
                ],
                "description": "Indicate that an app's step in a workflow completed execution.",
                "operationId": "workflows_stepCompleted",
                "security": [
                    {
                        "slackAuth": [
                            "workflow.steps:execute"
                        ]
                    }
                ]
            }
        },
        "/workflows.stepFailed": {
            "get": {
                "tags": [
                    "workflows"
                ],
                "description": "Indicate that an app's step in a workflow failed to execute.",
                "operationId": "workflows_stepFailed",
                "security": [
                    {
                        "slackAuth": [
                            "workflow.steps:execute"
                        ]
                    }
                ]
            }
        },
        "/workflows.updateStep": {
            "get": {
                "tags": [
                    "workflows"
                ],
                "description": "Update the configuration for a workflow extension step.",
                "operationId": "workflows_updateStep",
                "security": [
                    {
                        "slackAuth": [
                            "workflow.steps:execute"
                        ]
                    }
                ]
            }
        }
    }
}