{
  "openapi": "3.0.1",
  "info": {
    "title": "Slack Web API",
    "description": "One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.",
    "contact": {
      "name": "Slack developer relations",
      "url": "https://api.slack.com/support"
    },
    "version": "1.7.0"
  },
  "servers": [
    {
      "url": "https://slack.com/api"
    }
  ],
  "tags": [],
  "paths": {
    "/admin.apps.approve": {
      "post": {
        "tags": [
          "admin.apps",
          "admin"
        ],
        "description": "Approve an app for installation on a workspace.",
        "operationId": "admin_apps_approve",
        "security": [
          {
            "slackAuth": [
              "admin.apps:write"
            ]
          }
        ]
      }
    },
    "/admin.apps.approved.list": {
      "get": {
        "tags": [
          "admin.apps.approved",
          "admin"
        ],
        "description": "List approved apps for an org or workspace.",
        "operationId": "admin_apps_approved_list",
        "security": [
          {
            "slackAuth": [
              "admin.apps:read"
            ]
          }
        ]
      }
    },
    "/admin.apps.requests.list": {
      "get": {
        "tags": [
          "admin.apps.requests",
          "admin"
        ],
        "description": "List app requests for a team/workspace.",
        "operationId": "admin_apps_requests_list",
        "security": [
          {
            "slackAuth": [
              "admin.apps:read"
            ]
          }
        ]
      }
    },
    "/admin.apps.restrict": {
      "post": {
        "tags": [
          "admin.apps",
          "admin"
        ],
        "description": "Restrict an app for installation on a workspace.",
        "operationId": "admin_apps_restrict",
        "security": [
          {
            "slackAuth": [
              "admin.apps:write"
            ]
          }
        ]
      }
    },
    "/admin.apps.restricted.list": {
      "get": {
        "tags": [
          "admin.apps.restricted",
          "admin"
        ],
        "description": "List restricted apps for an org or workspace.",
        "operationId": "admin_apps_restricted_list",
        "security": [
          {
            "slackAuth": [
              "admin.apps:read"
            ]
          }
        ]
      }
    },
    "/admin.conversations.archive": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Archive a public or private channel.",
        "operationId": "admin_conversations_archive",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.convertToPrivate": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Convert a public channel to a private channel.",
        "operationId": "admin_conversations_convertToPrivate",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.create": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Create a public or private channel-based conversation.",
        "operationId": "admin_conversations_create",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.delete": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Delete a public or private channel.",
        "operationId": "admin_conversations_delete",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.disconnectShared": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Disconnect a connected channel from one or more workspaces.",
        "operationId": "admin_conversations_disconnectShared",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.ekm.listOriginalConnectedChannelInfo": {
      "get": {
        "tags": [
          "admin.conversations.ekm",
          "admin"
        ],
        "description": "List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM.",
        "operationId": "admin_conversations_ekm_listOriginalConnectedChannelInfo",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:read"
            ]
          }
        ]
      }
    },
    "/admin.conversations.getConversationPrefs": {
      "get": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Get conversation preferences for a public or private channel.",
        "operationId": "admin_conversations_getConversationPrefs",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:read"
            ]
          }
        ]
      }
    },
    "/admin.conversations.getTeams": {
      "get": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Get all the workspaces a given public or private channel is connected to within this Enterprise org.",
        "operationId": "admin_conversations_getTeams",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:read"
            ]
          }
        ]
      }
    },
    "/admin.conversations.invite": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Invite a user to a public or private channel.",
        "operationId": "admin_conversations_invite",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.rename": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Rename a public or private channel.",
        "operationId": "admin_conversations_rename",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.restrictAccess.addGroup": {
      "post": {
        "tags": [
          "admin.conversations.restrictAccess",
          "admin"
        ],
        "description": "Add an allowlist of IDP groups for accessing a channel",
        "operationId": "admin_conversations_restrictAccess_addGroup",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.restrictAccess.listGroups": {
      "get": {
        "tags": [
          "admin.conversations.restrictAccess",
          "admin"
        ],
        "description": "List all IDP Groups linked to a channel",
        "operationId": "admin_conversations_restrictAccess_listGroups",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:read"
            ]
          }
        ]
      }
    },
    "/admin.conversations.restrictAccess.removeGroup": {
      "post": {
        "tags": [
          "admin.conversations.restrictAccess",
          "admin"
        ],
        "description": "Remove a linked IDP group linked from a private channel",
        "operationId": "admin_conversations_restrictAccess_removeGroup",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.search": {
      "get": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Search for public or private channels in an Enterprise organization.",
        "operationId": "admin_conversations_search",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:read"
            ]
          }
        ]
      }
    },
    "/admin.conversations.setConversationPrefs": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Set the posting permissions for a public or private channel.",
        "operationId": "admin_conversations_setConversationPrefs",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.setTeams": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Set the workspaces in an Enterprise grid org that connect to a public or private channel.",
        "operationId": "admin_conversations_setTeams",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.conversations.unarchive": {
      "post": {
        "tags": [
          "admin.conversations",
          "admin"
        ],
        "description": "Unarchive a public or private channel.",
        "operationId": "admin_conversations_unarchive",
        "security": [
          {
            "slackAuth": [
              "admin.conversations:write"
            ]
          }
        ]
      }
    },
    "/admin.emoji.add": {
      "post": {
        "tags": [
          "admin.emoji",
          "admin"
        ],
        "description": "Add an emoji.",
        "operationId": "admin_emoji_add",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.emoji.addAlias": {
      "post": {
        "tags": [
          "admin.emoji",
          "admin"
        ],
        "description": "Add an emoji alias.",
        "operationId": "admin_emoji_addAlias",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.emoji.list": {
      "get": {
        "tags": [
          "admin.emoji",
          "admin"
        ],
        "description": "List emoji for an Enterprise Grid organization.",
        "operationId": "admin_emoji_list",
        "security": [
          {
            "slackAuth": [
              "admin.teams:read"
            ]
          }
        ]
      }
    },
    "/admin.emoji.remove": {
      "post": {
        "tags": [
          "admin.emoji",
          "admin"
        ],
        "description": "Remove an emoji across an Enterprise Grid organization",
        "operationId": "admin_emoji_remove",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.emoji.rename": {
      "post": {
        "tags": [
          "admin.emoji",
          "admin"
        ],
        "description": "Rename an emoji.",
        "operationId": "admin_emoji_rename",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.inviteRequests.approve": {
      "post": {
        "tags": [
          "admin.inviteRequests",
          "admin"
        ],
        "description": "Approve a workspace invite request.",
        "operationId": "admin_inviteRequests_approve",
        "security": [
          {
            "slackAuth": [
              "admin.invites:write"
            ]
          }
        ]
      }
    },
    "/admin.inviteRequests.approved.list": {
      "get": {
        "tags": [
          "admin.inviteRequests.approved",
          "admin"
        ],
        "description": "List all approved workspace invite requests.",
        "operationId": "admin_inviteRequests_approved_list",
        "security": [
          {
            "slackAuth": [
              "admin.invites:read"
            ]
          }
        ]
      }
    },
    "/admin.inviteRequests.denied.list": {
      "get": {
        "tags": [
          "admin.inviteRequests.denied",
          "admin"
        ],
        "description": "List all denied workspace invite requests.",
        "operationId": "admin_inviteRequests_denied_list",
        "security": [
          {
            "slackAuth": [
              "admin.invites:read"
            ]
          }
        ]
      }
    },
    "/admin.inviteRequests.deny": {
      "post": {
        "tags": [
          "admin.inviteRequests",
          "admin"
        ],
        "description": "Deny a workspace invite request.",
        "operationId": "admin_inviteRequests_deny",
        "security": [
          {
            "slackAuth": [
              "admin.invites:write"
            ]
          }
        ]
      }
    },
    "/admin.inviteRequests.list": {
      "get": {
        "tags": [
          "admin.inviteRequests",
          "admin"
        ],
        "description": "List all pending workspace invite requests.",
        "operationId": "admin_inviteRequests_list",
        "security": [
          {
            "slackAuth": [
              "admin.invites:read"
            ]
          }
        ]
      }
    },
    "/admin.teams.admins.list": {
      "get": {
        "tags": [
          "admin.teams.admins",
          "admin"
        ],
        "description": "List all of the admins on a given workspace.",
        "operationId": "admin_teams_admins_list",
        "security": [
          {
            "slackAuth": [
              "admin.teams:read"
            ]
          }
        ]
      }
    },
    "/admin.teams.create": {
      "post": {
        "tags": [
          "admin.teams",
          "admin"
        ],
        "description": "Create an Enterprise team.",
        "operationId": "admin_teams_create",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.teams.list": {
      "get": {
        "tags": [
          "admin.teams",
          "admin"
        ],
        "description": "List all teams on an Enterprise organization",
        "operationId": "admin_teams_list",
        "security": [
          {
            "slackAuth": [
              "admin.teams:read"
            ]
          }
        ]
      }
    },
    "/admin.teams.owners.list": {
      "get": {
        "tags": [
          "admin.teams.owners",
          "admin"
        ],
        "description": "List all of the owners on a given workspace.",
        "operationId": "admin_teams_owners_list",
        "security": [
          {
            "slackAuth": [
              "admin.teams:read"
            ]
          }
        ]
      }
    },
    "/admin.teams.settings.info": {
      "get": {
        "tags": [
          "admin.teams.settings",
          "admin"
        ],
        "description": "Fetch information about settings in a workspace",
        "operationId": "admin_teams_settings_info",
        "security": [
          {
            "slackAuth": [
              "admin.teams:read"
            ]
          }
        ]
      }
    },
    "/admin.teams.settings.setDefaultChannels": {
      "post": {
        "tags": [
          "admin.teams.settings",
          "admin"
        ],
        "description": "Set the default channels of a workspace.",
        "operationId": "admin_teams_settings_setDefaultChannels",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.teams.settings.setDescription": {
      "post": {
        "tags": [
          "admin.teams.settings",
          "admin"
        ],
        "description": "Set the description of a given workspace.",
        "operationId": "admin_teams_settings_setDescription",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.teams.settings.setDiscoverability": {
      "post": {
        "tags": [
          "admin.teams.settings",
          "admin"
        ],
        "description": "An API method that allows admins to set the discoverability of a given workspace",
        "operationId": "admin_teams_settings_setDiscoverability",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.teams.settings.setIcon": {
      "post": {
        "tags": [
          "admin.teams.settings",
          "admin"
        ],
        "description": "Sets the icon of a workspace.",
        "operationId": "admin_teams_settings_setIcon",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.teams.settings.setName": {
      "post": {
        "tags": [
          "admin.teams.settings",
          "admin"
        ],
        "description": "Set the name of a given workspace.",
        "operationId": "admin_teams_settings_setName",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.usergroups.addChannels": {
      "post": {
        "tags": [
          "admin.usergroups",
          "admin"
        ],
        "description": "Add one or more default channels to an IDP group.",
        "operationId": "admin_usergroups_addChannels",
        "security": [
          {
            "slackAuth": [
              "admin.usergroups:write"
            ]
          }
        ]
      }
    },
    "/admin.usergroups.addTeams": {
      "post": {
        "tags": [
          "admin.usergroups",
          "admin"
        ],
        "description": "Associate one or more default workspaces with an organization-wide IDP group.",
        "operationId": "admin_usergroups_addTeams",
        "security": [
          {
            "slackAuth": [
              "admin.teams:write"
            ]
          }
        ]
      }
    },
    "/admin.usergroups.listChannels": {
      "get": {
        "tags": [
          "admin.usergroups",
          "admin"
        ],
        "description": "List the channels linked to an org-level IDP group (user group).",
        "operationId": "admin_usergroups_listChannels",
        "security": [
          {
            "slackAuth": [
              "admin.usergroups:read"
            ]
          }
        ]
      }
    },
    "/admin.usergroups.removeChannels": {
      "post": {
        "tags": [
          "admin.usergroups",
          "admin"
        ],
        "description": "Remove one or more default channels from an org-level IDP group (user group).",
        "operationId": "admin_usergroups_removeChannels",
        "security": [
          {
            "slackAuth": [
              "admin.usergroups:write"
            ]
          }
        ]
      }
    },
    "/admin.users.assign": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Add an Enterprise user to a workspace.",
        "operationId": "admin_users_assign",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.invite": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Invite a user to a workspace.",
        "operationId": "admin_users_invite",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.list": {
      "get": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "List users on a workspace",
        "operationId": "admin_users_list",
        "security": [
          {
            "slackAuth": [
              "admin.users:read"
            ]
          }
        ]
      }
    },
    "/admin.users.remove": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Remove a user from a workspace.",
        "operationId": "admin_users_remove",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.session.invalidate": {
      "post": {
        "tags": [
          "admin.users.session",
          "admin"
        ],
        "description": "Invalidate a single session for a user by session_id",
        "operationId": "admin_users_session_invalidate",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.session.reset": {
      "post": {
        "tags": [
          "admin.users.session",
          "admin"
        ],
        "description": "Wipes all valid sessions on all devices for a given user",
        "operationId": "admin_users_session_reset",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.setAdmin": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Set an existing guest, regular user, or owner to be an admin user.",
        "operationId": "admin_users_setAdmin",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.setExpiration": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Set an expiration for a guest user",
        "operationId": "admin_users_setExpiration",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.setOwner": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Set an existing guest, regular user, or admin user to be a workspace owner.",
        "operationId": "admin_users_setOwner",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/admin.users.setRegular": {
      "post": {
        "tags": [
          "admin.users",
          "admin"
        ],
        "description": "Set an existing guest user, admin user, or owner to be a regular user.",
        "operationId": "admin_users_setRegular",
        "security": [
          {
            "slackAuth": [
              "admin.users:write"
            ]
          }
        ]
      }
    },
    "/api.test": {
      "get": {
        "tags": [
          "api"
        ],
        "description": "Checks API calling code.",
        "operationId": "api_test",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.event.authorizations.list": {
      "get": {
        "tags": [
          "apps.event.authorizations",
          "apps"
        ],
        "description": "Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to.",
        "operationId": "apps_event_authorizations_list",
        "security": [
          {
            "slackAuth": [
              "authorizations:read"
            ]
          }
        ]
      }
    },
    "/apps.permissions.info": {
      "get": {
        "tags": [
          "apps.permissions",
          "apps"
        ],
        "description": "Returns list of permissions this app has on a team.",
        "operationId": "apps_permissions_info",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.permissions.request": {
      "get": {
        "tags": [
          "apps.permissions",
          "apps"
        ],
        "description": "Allows an app to request additional scopes",
        "operationId": "apps_permissions_request",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.permissions.resources.list": {
      "get": {
        "tags": [
          "apps.permissions.resources",
          "apps"
        ],
        "description": "Returns list of resource grants this app has on a team.",
        "operationId": "apps_permissions_resources_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.permissions.scopes.list": {
      "get": {
        "tags": [
          "apps.permissions.scopes",
          "apps"
        ],
        "description": "Returns list of scopes this app has on a team.",
        "operationId": "apps_permissions_scopes_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.permissions.users.list": {
      "get": {
        "tags": [
          "apps.permissions.users",
          "apps"
        ],
        "description": "Returns list of user grants and corresponding scopes this app has on a team.",
        "operationId": "apps_permissions_users_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.permissions.users.request": {
      "get": {
        "tags": [
          "apps.permissions.users",
          "apps"
        ],
        "description": "Enables an app to trigger a permissions modal to grant an app access to a user access scope.",
        "operationId": "apps_permissions_users_request",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/apps.uninstall": {
      "get": {
        "tags": [
          "apps"
        ],
        "description": "Uninstalls your app from a workspace.",
        "operationId": "apps_uninstall",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/auth.revoke": {
      "get": {
        "tags": [
          "auth"
        ],
        "description": "Revokes a token.",
        "operationId": "auth_revoke",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/auth.test": {
      "get": {
        "tags": [
          "auth"
        ],
        "description": "Checks authentication & identity.",
        "operationId": "auth_test",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/bots.info": {
      "get": {
        "tags": [
          "bots"
        ],
        "description": "Gets information about a bot user.",
        "operationId": "bots_info",
        "security": [
          {
            "slackAuth": [
              "users:read"
            ]
          }
        ]
      }
    },
    "/calls.add": {
      "post": {
        "tags": [
          "calls"
        ],
        "description": "Registers a new Call.",
        "operationId": "calls_add",
        "security": [
          {
            "slackAuth": [
              "calls:write"
            ]
          }
        ]
      }
    },
    "/calls.end": {
      "post": {
        "tags": [
          "calls"
        ],
        "description": "Ends a Call.",
        "operationId": "calls_end",
        "security": [
          {
            "slackAuth": [
              "calls:write"
            ]
          }
        ]
      }
    },
    "/calls.info": {
      "get": {
        "tags": [
          "calls"
        ],
        "description": "Returns information about a Call.",
        "operationId": "calls_info",
        "security": [
          {
            "slackAuth": [
              "calls:read"
            ]
          }
        ]
      }
    },
    "/calls.participants.add": {
      "post": {
        "tags": [
          "calls.participants",
          "calls"
        ],
        "description": "Registers new participants added to a Call.",
        "operationId": "calls_participants_add",
        "security": [
          {
            "slackAuth": [
              "calls:write"
            ]
          }
        ]
      }
    },
    "/calls.participants.remove": {
      "post": {
        "tags": [
          "calls.participants",
          "calls"
        ],
        "description": "Registers participants removed from a Call.",
        "operationId": "calls_participants_remove",
        "security": [
          {
            "slackAuth": [
              "calls:write"
            ]
          }
        ]
      }
    },
    "/calls.update": {
      "post": {
        "tags": [
          "calls"
        ],
        "description": "Updates information about a Call.",
        "operationId": "calls_update",
        "security": [
          {
            "slackAuth": [
              "calls:write"
            ]
          }
        ]
      }
    },
    "/chat.delete": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Deletes a message.",
        "operationId": "chat_delete",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/chat.deleteScheduledMessage": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Deletes a pending scheduled message from the queue.",
        "operationId": "chat_deleteScheduledMessage",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/chat.getPermalink": {
      "get": {
        "tags": [
          "chat"
        ],
        "description": "Retrieve a permalink URL for a specific extant message",
        "operationId": "chat_getPermalink",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/chat.meMessage": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Share a me message into a channel.",
        "operationId": "chat_meMessage",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/chat.postEphemeral": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Sends an ephemeral message to a user in a channel.",
        "operationId": "chat_postEphemeral",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/chat.postMessage": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Sends a message to a channel.",
        "operationId": "chat_postMessage",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/chat.scheduleMessage": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Schedules a message to be sent to a channel.",
        "operationId": "chat_scheduleMessage",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/chat.scheduledMessages.list": {
      "get": {
        "tags": [
          "chat.scheduledMessages",
          "chat"
        ],
        "description": "Returns a list of scheduled messages.",
        "operationId": "chat_scheduledMessages_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/chat.unfurl": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Provide custom unfurl behavior for user-posted URLs",
        "operationId": "chat_unfurl",
        "security": [
          {
            "slackAuth": [
              "links:write"
            ]
          }
        ]
      }
    },
    "/chat.update": {
      "post": {
        "tags": [
          "chat"
        ],
        "description": "Updates a message.",
        "operationId": "chat_update",
        "security": [
          {
            "slackAuth": [
              "chat:write:user",
              "chat:write:bot"
            ]
          }
        ]
      }
    },
    "/conversations.archive": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Archives a conversation.",
        "operationId": "conversations_archive",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.close": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Closes a direct message or multi-person direct message.",
        "operationId": "conversations_close",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.create": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Initiates a public or private channel-based conversation",
        "operationId": "conversations_create",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.history": {
      "get": {
        "tags": [
          "conversations"
        ],
        "description": "Fetches a conversation's history of messages and events.",
        "operationId": "conversations_history",
        "security": [
          {
            "slackAuth": [
              "channels:history",
              "groups:history",
              "im:history",
              "mpim:history"
            ]
          }
        ]
      }
    },
    "/conversations.info": {
      "get": {
        "tags": [
          "conversations"
        ],
        "description": "Retrieve information about a conversation.",
        "operationId": "conversations_info",
        "security": [
          {
            "slackAuth": [
              "channels:read",
              "groups:read",
              "im:read",
              "mpim:read"
            ]
          }
        ]
      }
    },
    "/conversations.invite": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Invites users to a channel.",
        "operationId": "conversations_invite",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.join": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Joins an existing conversation.",
        "operationId": "conversations_join",
        "security": [
          {
            "slackAuth": [
              "channels:write"
            ]
          }
        ]
      }
    },
    "/conversations.kick": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Removes a user from a conversation.",
        "operationId": "conversations_kick",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.leave": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Leaves a conversation.",
        "operationId": "conversations_leave",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.list": {
      "get": {
        "tags": [
          "conversations"
        ],
        "description": "Lists all channels in a Slack team.",
        "operationId": "conversations_list",
        "security": [
          {
            "slackAuth": [
              "channels:read",
              "groups:read",
              "im:read",
              "mpim:read"
            ]
          }
        ]
      }
    },
    "/conversations.mark": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Sets the read cursor in a channel.",
        "operationId": "conversations_mark",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.members": {
      "get": {
        "tags": [
          "conversations"
        ],
        "description": "Retrieve members of a conversation.",
        "operationId": "conversations_members",
        "security": [
          {
            "slackAuth": [
              "channels:read",
              "groups:read",
              "im:read",
              "mpim:read"
            ]
          }
        ]
      }
    },
    "/conversations.open": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Opens or resumes a direct message or multi-person direct message.",
        "operationId": "conversations_open",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.rename": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Renames a conversation.",
        "operationId": "conversations_rename",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.replies": {
      "get": {
        "tags": [
          "conversations"
        ],
        "description": "Retrieve a thread of messages posted to a conversation",
        "operationId": "conversations_replies",
        "security": [
          {
            "slackAuth": [
              "channels:history",
              "groups:history",
              "im:history",
              "mpim:history"
            ]
          }
        ]
      }
    },
    "/conversations.setPurpose": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Sets the purpose for a conversation.",
        "operationId": "conversations_setPurpose",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.setTopic": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Sets the topic for a conversation.",
        "operationId": "conversations_setTopic",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/conversations.unarchive": {
      "post": {
        "tags": [
          "conversations"
        ],
        "description": "Reverses conversation archival.",
        "operationId": "conversations_unarchive",
        "security": [
          {
            "slackAuth": [
              "channels:write",
              "groups:write",
              "im:write",
              "mpim:write"
            ]
          }
        ]
      }
    },
    "/dialog.open": {
      "get": {
        "tags": [
          "dialog"
        ],
        "description": "Open a dialog with a user",
        "operationId": "dialog_open",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/dnd.endDnd": {
      "post": {
        "tags": [
          "dnd"
        ],
        "description": "Ends the current user's Do Not Disturb session immediately.",
        "operationId": "dnd_endDnd",
        "security": [
          {
            "slackAuth": [
              "dnd:write"
            ]
          }
        ]
      }
    },
    "/dnd.endSnooze": {
      "post": {
        "tags": [
          "dnd"
        ],
        "description": "Ends the current user's snooze mode immediately.",
        "operationId": "dnd_endSnooze",
        "security": [
          {
            "slackAuth": [
              "dnd:write"
            ]
          }
        ]
      }
    },
    "/dnd.info": {
      "get": {
        "tags": [
          "dnd"
        ],
        "description": "Retrieves a user's current Do Not Disturb status.",
        "operationId": "dnd_info",
        "security": [
          {
            "slackAuth": [
              "dnd:read"
            ]
          }
        ]
      }
    },
    "/dnd.setSnooze": {
      "post": {
        "tags": [
          "dnd"
        ],
        "description": "Turns on Do Not Disturb mode for the current user, or changes its duration.",
        "operationId": "dnd_setSnooze",
        "security": [
          {
            "slackAuth": [
              "dnd:write"
            ]
          }
        ]
      }
    },
    "/dnd.teamInfo": {
      "get": {
        "tags": [
          "dnd"
        ],
        "description": "Retrieves the Do Not Disturb status for up to 50 users on a team.",
        "operationId": "dnd_teamInfo",
        "security": [
          {
            "slackAuth": [
              "dnd:read"
            ]
          }
        ]
      }
    },
    "/emoji.list": {
      "get": {
        "tags": [
          "emoji"
        ],
        "description": "Lists custom emoji for a team.",
        "operationId": "emoji_list",
        "security": [
          {
            "slackAuth": [
              "emoji:read"
            ]
          }
        ]
      }
    },
    "/files.comments.delete": {
      "post": {
        "tags": [
          "files.comments",
          "files"
        ],
        "description": "Deletes an existing comment on a file.",
        "operationId": "files_comments_delete",
        "security": [
          {
            "slackAuth": [
              "files:write:user"
            ]
          }
        ]
      }
    },
    "/files.delete": {
      "post": {
        "tags": [
          "files"
        ],
        "description": "Deletes a file.",
        "operationId": "files_delete",
        "security": [
          {
            "slackAuth": [
              "files:write:user"
            ]
          }
        ]
      }
    },
    "/files.info": {
      "get": {
        "tags": [
          "files"
        ],
        "description": "Gets information about a file.",
        "operationId": "files_info",
        "security": [
          {
            "slackAuth": [
              "files:read"
            ]
          }
        ]
      }
    },
    "/files.list": {
      "get": {
        "tags": [
          "files"
        ],
        "description": "List for a team, in a channel, or from a user with applied filters.",
        "operationId": "files_list",
        "security": [
          {
            "slackAuth": [
              "files:read"
            ]
          }
        ]
      }
    },
    "/files.remote.add": {
      "post": {
        "tags": [
          "files.remote",
          "files"
        ],
        "description": "Adds a file from a remote service",
        "operationId": "files_remote_add",
        "security": [
          {
            "slackAuth": [
              "remote_files:write"
            ]
          }
        ]
      }
    },
    "/files.remote.info": {
      "get": {
        "tags": [
          "files.remote",
          "files"
        ],
        "description": "Retrieve information about a remote file added to Slack",
        "operationId": "files_remote_info",
        "security": [
          {
            "slackAuth": [
              "remote_files:read"
            ]
          }
        ]
      }
    },
    "/files.remote.list": {
      "get": {
        "tags": [
          "files.remote",
          "files"
        ],
        "description": "Retrieve information about a remote file added to Slack",
        "operationId": "files_remote_list",
        "security": [
          {
            "slackAuth": [
              "remote_files:read"
            ]
          }
        ]
      }
    },
    "/files.remote.remove": {
      "post": {
        "tags": [
          "files.remote",
          "files"
        ],
        "description": "Remove a remote file.",
        "operationId": "files_remote_remove",
        "security": [
          {
            "slackAuth": [
              "remote_files:write"
            ]
          }
        ]
      }
    },
    "/files.remote.share": {
      "get": {
        "tags": [
          "files.remote",
          "files"
        ],
        "description": "Share a remote file into a channel.",
        "operationId": "files_remote_share",
        "security": [
          {
            "slackAuth": [
              "remote_files:share"
            ]
          }
        ]
      }
    },
    "/files.remote.update": {
      "post": {
        "tags": [
          "files.remote",
          "files"
        ],
        "description": "Updates an existing remote file.",
        "operationId": "files_remote_update",
        "security": [
          {
            "slackAuth": [
              "remote_files:write"
            ]
          }
        ]
      }
    },
    "/files.revokePublicURL": {
      "post": {
        "tags": [
          "files"
        ],
        "description": "Revokes public/external sharing access for a file",
        "operationId": "files_revokePublicURL",
        "security": [
          {
            "slackAuth": [
              "files:write:user"
            ]
          }
        ]
      }
    },
    "/files.sharedPublicURL": {
      "post": {
        "tags": [
          "files"
        ],
        "description": "Enables a file for public/external sharing.",
        "operationId": "files_sharedPublicURL",
        "security": [
          {
            "slackAuth": [
              "files:write:user"
            ]
          }
        ]
      }
    },
    "/files.upload": {
      "post": {
        "tags": [
          "files"
        ],
        "description": "Uploads or creates a file.",
        "operationId": "files_upload",
        "security": [
          {
            "slackAuth": [
              "files:write:user"
            ]
          }
        ]
      }
    },
    "/migration.exchange": {
      "get": {
        "tags": [
          "migration"
        ],
        "description": "For Enterprise Grid workspaces, map local user IDs to global user IDs",
        "operationId": "migration_exchange",
        "security": [
          {
            "slackAuth": [
              "tokens.basic"
            ]
          }
        ]
      }
    },
    "/oauth.access": {
      "get": {
        "tags": [
          "oauth"
        ],
        "description": "Exchanges a temporary OAuth verifier code for an access token.",
        "operationId": "oauth_access",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/oauth.token": {
      "get": {
        "tags": [
          "oauth"
        ],
        "description": "Exchanges a temporary OAuth verifier code for a workspace token.",
        "operationId": "oauth_token",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/oauth.v2.access": {
      "get": {
        "tags": [
          "oauth.v2",
          "oauth"
        ],
        "description": "Exchanges a temporary OAuth verifier code for an access token.",
        "operationId": "oauth_v2_access",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/pins.add": {
      "post": {
        "tags": [
          "pins"
        ],
        "description": "Pins an item to a channel.",
        "operationId": "pins_add",
        "security": [
          {
            "slackAuth": [
              "pins:write"
            ]
          }
        ]
      }
    },
    "/pins.list": {
      "get": {
        "tags": [
          "pins"
        ],
        "description": "Lists items pinned to a channel.",
        "operationId": "pins_list",
        "security": [
          {
            "slackAuth": [
              "pins:read"
            ]
          }
        ]
      }
    },
    "/pins.remove": {
      "post": {
        "tags": [
          "pins"
        ],
        "description": "Un-pins an item from a channel.",
        "operationId": "pins_remove",
        "security": [
          {
            "slackAuth": [
              "pins:write"
            ]
          }
        ]
      }
    },
    "/reactions.add": {
      "post": {
        "tags": [
          "reactions"
        ],
        "description": "Adds a reaction to an item.",
        "operationId": "reactions_add",
        "security": [
          {
            "slackAuth": [
              "reactions:write"
            ]
          }
        ]
      }
    },
    "/reactions.get": {
      "get": {
        "tags": [
          "reactions"
        ],
        "description": "Gets reactions for an item.",
        "operationId": "reactions_get",
        "security": [
          {
            "slackAuth": [
              "reactions:read"
            ]
          }
        ]
      }
    },
    "/reactions.list": {
      "get": {
        "tags": [
          "reactions"
        ],
        "description": "Lists reactions made by a user.",
        "operationId": "reactions_list",
        "security": [
          {
            "slackAuth": [
              "reactions:read"
            ]
          }
        ]
      }
    },
    "/reactions.remove": {
      "post": {
        "tags": [
          "reactions"
        ],
        "description": "Removes a reaction from an item.",
        "operationId": "reactions_remove",
        "security": [
          {
            "slackAuth": [
              "reactions:write"
            ]
          }
        ]
      }
    },
    "/reminders.add": {
      "post": {
        "tags": [
          "reminders"
        ],
        "description": "Creates a reminder.",
        "operationId": "reminders_add",
        "security": [
          {
            "slackAuth": [
              "reminders:write"
            ]
          }
        ]
      }
    },
    "/reminders.complete": {
      "post": {
        "tags": [
          "reminders"
        ],
        "description": "Marks a reminder as complete.",
        "operationId": "reminders_complete",
        "security": [
          {
            "slackAuth": [
              "reminders:write"
            ]
          }
        ]
      }
    },
    "/reminders.delete": {
      "post": {
        "tags": [
          "reminders"
        ],
        "description": "Deletes a reminder.",
        "operationId": "reminders_delete",
        "security": [
          {
            "slackAuth": [
              "reminders:write"
            ]
          }
        ]
      }
    },
    "/reminders.info": {
      "get": {
        "tags": [
          "reminders"
        ],
        "description": "Gets information about a reminder.",
        "operationId": "reminders_info",
        "security": [
          {
            "slackAuth": [
              "reminders:read"
            ]
          }
        ]
      }
    },
    "/reminders.list": {
      "get": {
        "tags": [
          "reminders"
        ],
        "description": "Lists all reminders created by or for a given user.",
        "operationId": "reminders_list",
        "security": [
          {
            "slackAuth": [
              "reminders:read"
            ]
          }
        ]
      }
    },
    "/rtm.connect": {
      "get": {
        "tags": [
          "rtm"
        ],
        "description": "Starts a Real Time Messaging session.",
        "operationId": "rtm_connect",
        "security": [
          {
            "slackAuth": [
              "rtm:stream"
            ]
          }
        ]
      }
    },
    "/search.messages": {
      "get": {
        "tags": [
          "search"
        ],
        "description": "Searches for messages matching a query.",
        "operationId": "search_messages",
        "security": [
          {
            "slackAuth": [
              "search:read"
            ]
          }
        ]
      }
    },
    "/stars.add": {
      "post": {
        "tags": [
          "stars"
        ],
        "description": "Adds a star to an item.",
        "operationId": "stars_add",
        "security": [
          {
            "slackAuth": [
              "stars:write"
            ]
          }
        ]
      }
    },
    "/stars.list": {
      "get": {
        "tags": [
          "stars"
        ],
        "description": "Lists stars for a user.",
        "operationId": "stars_list",
        "security": [
          {
            "slackAuth": [
              "stars:read"
            ]
          }
        ]
      }
    },
    "/stars.remove": {
      "post": {
        "tags": [
          "stars"
        ],
        "description": "Removes a star from an item.",
        "operationId": "stars_remove",
        "security": [
          {
            "slackAuth": [
              "stars:write"
            ]
          }
        ]
      }
    },
    "/team.accessLogs": {
      "get": {
        "tags": [
          "team"
        ],
        "description": "Gets the access logs for the current team.",
        "operationId": "team_accessLogs",
        "security": [
          {
            "slackAuth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/team.billableInfo": {
      "get": {
        "tags": [
          "team"
        ],
        "description": "Gets billable users information for the current team.",
        "operationId": "team_billableInfo",
        "security": [
          {
            "slackAuth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/team.info": {
      "get": {
        "tags": [
          "team"
        ],
        "description": "Gets information about the current team.",
        "operationId": "team_info",
        "security": [
          {
            "slackAuth": [
              "team:read"
            ]
          }
        ]
      }
    },
    "/team.integrationLogs": {
      "get": {
        "tags": [
          "team"
        ],
        "description": "Gets the integration logs for the current team.",
        "operationId": "team_integrationLogs",
        "security": [
          {
            "slackAuth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/team.profile.get": {
      "get": {
        "tags": [
          "team.profile",
          "team"
        ],
        "description": "Retrieve a team's profile.",
        "operationId": "team_profile_get",
        "security": [
          {
            "slackAuth": [
              "users.profile:read"
            ]
          }
        ]
      }
    },
    "/usergroups.create": {
      "post": {
        "tags": [
          "usergroups"
        ],
        "description": "Create a User Group",
        "operationId": "usergroups_create",
        "security": [
          {
            "slackAuth": [
              "usergroups:write"
            ]
          }
        ]
      }
    },
    "/usergroups.disable": {
      "post": {
        "tags": [
          "usergroups"
        ],
        "description": "Disable an existing User Group",
        "operationId": "usergroups_disable",
        "security": [
          {
            "slackAuth": [
              "usergroups:write"
            ]
          }
        ]
      }
    },
    "/usergroups.enable": {
      "post": {
        "tags": [
          "usergroups"
        ],
        "description": "Enable a User Group",
        "operationId": "usergroups_enable",
        "security": [
          {
            "slackAuth": [
              "usergroups:write"
            ]
          }
        ]
      }
    },
    "/usergroups.list": {
      "get": {
        "tags": [
          "usergroups"
        ],
        "description": "List all User Groups for a team",
        "operationId": "usergroups_list",
        "security": [
          {
            "slackAuth": [
              "usergroups:read"
            ]
          }
        ]
      }
    },
    "/usergroups.update": {
      "post": {
        "tags": [
          "usergroups"
        ],
        "description": "Update an existing User Group",
        "operationId": "usergroups_update",
        "security": [
          {
            "slackAuth": [
              "usergroups:write"
            ]
          }
        ]
      }
    },
    "/usergroups.users.list": {
      "get": {
        "tags": [
          "usergroups.users",
          "usergroups"
        ],
        "description": "List all users in a User Group",
        "operationId": "usergroups_users_list",
        "security": [
          {
            "slackAuth": [
              "usergroups:read"
            ]
          }
        ]
      }
    },
    "/usergroups.users.update": {
      "post": {
        "tags": [
          "usergroups.users",
          "usergroups"
        ],
        "description": "Update the list of users for a User Group",
        "operationId": "usergroups_users_update",
        "security": [
          {
            "slackAuth": [
              "usergroups:write"
            ]
          }
        ]
      }
    },
    "/users.conversations": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "List conversations the calling user may access.",
        "operationId": "users_conversations",
        "security": [
          {
            "slackAuth": [
              "channels:read",
              "groups:read",
              "im:read",
              "mpim:read"
            ]
          }
        ]
      }
    },
    "/users.deletePhoto": {
      "post": {
        "tags": [
          "users"
        ],
        "description": "Delete the user profile photo",
        "operationId": "users_deletePhoto",
        "security": [
          {
            "slackAuth": [
              "users.profile:write"
            ]
          }
        ]
      }
    },
    "/users.getPresence": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "Gets user presence information.",
        "operationId": "users_getPresence",
        "security": [
          {
            "slackAuth": [
              "users:read"
            ]
          }
        ]
      }
    },
    "/users.identity": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "Get a user's identity.",
        "operationId": "users_identity",
        "security": [
          {
            "slackAuth": [
              "identity.basic"
            ]
          }
        ]
      }
    },
    "/users.info": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "Gets information about a user.",
        "operationId": "users_info",
        "security": [
          {
            "slackAuth": [
              "users:read"
            ]
          }
        ]
      }
    },
    "/users.list": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "Lists all users in a Slack team.",
        "operationId": "users_list",
        "security": [
          {
            "slackAuth": [
              "users:read"
            ]
          }
        ]
      }
    },
    "/users.lookupByEmail": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "Find a user with an email address.",
        "operationId": "users_lookupByEmail",
        "security": [
          {
            "slackAuth": [
              "users:read.email"
            ]
          }
        ]
      }
    },
    "/users.profile.get": {
      "get": {
        "tags": [
          "users.profile",
          "users"
        ],
        "description": "Retrieves a user's profile information.",
        "operationId": "users_profile_get",
        "security": [
          {
            "slackAuth": [
              "users.profile:read"
            ]
          }
        ]
      }
    },
    "/users.profile.set": {
      "post": {
        "tags": [
          "users.profile",
          "users"
        ],
        "description": "Set the profile information for a user.",
        "operationId": "users_profile_set",
        "security": [
          {
            "slackAuth": [
              "users.profile:write"
            ]
          }
        ]
      }
    },
    "/users.setActive": {
      "post": {
        "tags": [
          "users"
        ],
        "description": "Marked a user as active. Deprecated and non-functional.",
        "operationId": "users_setActive",
        "security": [
          {
            "slackAuth": [
              "users:write"
            ]
          }
        ]
      }
    },
    "/users.setPhoto": {
      "post": {
        "tags": [
          "users"
        ],
        "description": "Set the user profile photo",
        "operationId": "users_setPhoto",
        "security": [
          {
            "slackAuth": [
              "users.profile:write"
            ]
          }
        ]
      }
    },
    "/users.setPresence": {
      "post": {
        "tags": [
          "users"
        ],
        "description": "Manually sets user presence.",
        "operationId": "users_setPresence",
        "security": [
          {
            "slackAuth": [
              "users:write"
            ]
          }
        ]
      }
    },
    "/views.open": {
      "get": {
        "tags": [
          "views"
        ],
        "description": "Open a view for a user.",
        "operationId": "views_open",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/views.publish": {
      "get": {
        "tags": [
          "views"
        ],
        "description": "Publish a static view for a User.",
        "operationId": "views_publish",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/views.push": {
      "get": {
        "tags": [
          "views"
        ],
        "description": "Push a view onto the stack of a root view.",
        "operationId": "views_push",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/views.update": {
      "get": {
        "tags": [
          "views"
        ],
        "description": "Update an existing view.",
        "operationId": "views_update",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ]
      }
    },
    "/workflows.stepCompleted": {
      "get": {
        "tags": [
          "workflows"
        ],
        "description": "Indicate that an app's step in a workflow completed execution.",
        "operationId": "workflows_stepCompleted",
        "security": [
          {
            "slackAuth": [
              "workflow.steps:execute"
            ]
          }
        ]
      }
    },
    "/workflows.stepFailed": {
      "get": {
        "tags": [
          "workflows"
        ],
        "description": "Indicate that an app's step in a workflow failed to execute.",
        "operationId": "workflows_stepFailed",
        "security": [
          {
            "slackAuth": [
              "workflow.steps:execute"
            ]
          }
        ]
      }
    },
    "/workflows.updateStep": {
      "get": {
        "tags": [
          "workflows"
        ],
        "description": "Update the configuration for a workflow extension step.",
        "operationId": "workflows_updateStep",
        "security": [
          {
            "slackAuth": [
              "workflow.steps:execute"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "slackAuth": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://slack.com/oauth/authorize",
            "tokenUrl": "https://slack.com/api/oauth.access",
            "scopes": {
              "admin": "admin",
              "admin.apps:read": "admin.apps:read",
              "admin.apps:write": "admin.apps:write",
              "admin.conversations:read": "admin.conversations:read",
              "admin.conversations:write": "admin.conversations:write",
              "admin.invites:read": "admin.invites:read",
              "admin.invites:write": "admin.invites:write",
              "admin.teams:read": "admin.teams:read",
              "admin.teams:write": "admin.teams:write",
              "admin.usergroups:read": "admin.usergroups:read",
              "admin.usergroups:write": "admin.usergroups:write",
              "admin.users:read": "admin.users:read",
              "admin.users:write": "admin.users:write",
              "authorizations:read": "authorizations:read",
              "bot": "Bot user scope",
              "calls:read": "calls:read",
              "calls:write": "calls:write",
              "channels:history": "channels:history",
              "channels:manage": "channels:manage",
              "channels:read": "channels:read",
              "channels:write": "channels:write",
              "chat:write": "chat:write",
              "chat:write:bot": "Author messages as a bot",
              "chat:write:user": "Author messages as a user",
              "conversations:history": "conversations:history",
              "conversations:read": "conversations:read",
              "conversations:write": "conversations:write",
              "dnd:read": "dnd:read",
              "dnd:write": "dnd:write",
              "emoji:read": "emoji:read",
              "files:read": "files:read",
              "files:write:user": "files:write:user",
              "groups:history": "groups:history",
              "groups:read": "groups:read",
              "groups:write": "groups:write",
              "identity.basic": "identity.basic",
              "im:history": "im:history",
              "im:read": "im:read",
              "im:write": "im:write",
              "links:write": "links:write",
              "mpim:history": "mpim:history",
              "mpim:read": "mpim:read",
              "mpim:write": "mpim:write",
              "none": "No scope required",
              "pins:read": "pins:read",
              "pins:write": "pins:write",
              "reactions:read": "reactions:read",
              "reactions:write": "reactions:write",
              "reminders:read": "reminders:read",
              "reminders:write": "reminders:write",
              "remote_files:read": "remote_files:read",
              "remote_files:share": "remote_files:share",
              "remote_files:write": "remote_files:write",
              "rtm:stream": "rtm:stream",
              "search:read": "search:read",
              "stars:read": "stars:read",
              "stars:write": "stars:write",
              "team:read": "team:read",
              "tokens.basic": "tokens.basic",
              "usergroups:read": "usergroups:read",
              "usergroups:write": "usergroups:write",
              "users.profile:read": "users.profile:read",
              "users.profile:write": "users.profile:write",
              "users:read": "users:read",
              "users:read.email": "users:read.email",
              "users:write": "users:write",
              "workflow.steps:execute": "workflow.steps:execute"
            }
          }
        }
      }
    }
  }
}