image:
  file: .gitpod.Dockerfile
  context: .

tasks:
  - init: |
      mkdir -p ~/.ssh
      echo "Host github.com" > ~/.ssh/config
      echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
      chmod 600 ~/.ssh/config
      echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      
      # Add the SSH key to the SSH agent
      eval $(ssh-agent -s)
      ssh-add ~/.ssh/id_rsa