name: Lint Python Code Base

on: [pull_request]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd llm-server
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 llm-server/ --count --select=E9,F63,F7,F82 --show-source --statistics

